Update checkout_config

diff --git a/.cfg/checkout_config b/.cfg/checkout_config
--- a/.cfg/checkout_config
+++ b/.cfg/checkout_config
@@ -6,10 +6,14 @@ function config {
 mkdir -p .config-backup
 config checkout
 if [ $? = 0 ]; then
-  echo "Checked out config.";
+  echo "Checking out config.";
   else
     echo "Backing up pre-existing dot files.";
     config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | xargs -I{} sh -c 'cp --parents -f {} .config-backup/ ; rm -f {}'
 fi;
 config checkout
-config config status.showUntrackedFiles no
+if [ $? = 0 ]; then
+   config config status.showUntrackedFiles no
+else
+   echo "Error while checking out.";
+fi;
